import Nav from "@/components/nav";
import Head from "next/head";

interface PortfolioProps {}

const Portfolio: React.FC<PortfolioProps> = () => {
  return (
    <>
      <Head>
        <title>Aktindo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Nav active="portfolio" />{" "}
      </div>
    </>
  );
};

export default Portfolio;
